- name: backup vr_gw
  hosts: vr_gw
  vars:
    filedir_ansible: "/mnt/disk/backup/sd/vr-gw"
  tasks:
    - name: Create dirs for group of hosts
      ansible.builtin.file:
        path: "{{ filedir_ansible }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Create dirs for host
      ansible.builtin.file:
        path: "{{ filedir_ansible }}/{{ ansible_hostname }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Copy SHOREWALL config files
      shell: rsync --delete -avzR -e ssh root@{{ ansible_host }}:/etc/shorewall/ {{ filedir_ansible }}/{{ ansible_hostname }}
      delegate_to: localhost
    - name: Copy NETPLAN files
      shell: rsync --delete -avzR -e ssh root@{{ ansible_host }}:/etc/netplan/ {{ filedir_ansible }}/{{ ansible_hostname }}
      delegate_to: localhost
    - name: Copy OPENVPN files
      shell: rsync --delete -avzR -e ssh root@{{ ansible_host }}:/etc/openvpn/ {{ filedir_ansible }}/{{ ansible_hostname }}
      delegate_to: localhost
    - name: Copy CRONTAB file
      shell: rsync --delete -avzR -e ssh root@{{ ansible_host }}:/etc/crontab/ {{ filedir_ansible }}/{{ ansible_hostname }}
      delegate_to: localhost

- name: backup rdp_linux
  hosts: rdp_linux
  vars:
    filedir_ansible: /mnt/disk/backup/sd/rdp_linux/
  tasks:
    - name: Create dirs for group of hosts
      ansible.builtin.file:
        path: "{{ filedir_ansible }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Create dirs for host
      ansible.builtin.file:
        path: "{{ filedir_ansible }}/{{ ansible_hostname }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Copy ROOT/EXEC file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/root/exec/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy SHOREWALL files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/shorewall/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy NETPLAN file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/netplan/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy PROFILE file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/profile "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy CRONTAB file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/crontab "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy XRDP files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/xrdp "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy PASSWD file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/passwd "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy GROUP file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/group "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy SHADOW file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/shadow "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy FSTAB file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/fstab "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost

- name: backup gw_ts
  hosts: gw_ts
  vars:
    filedir_ansible: "/mnt/disk/backup/sd/gw_ts"
  tasks:
    - name: Create dirs for group of hosts
      ansible.builtin.file:
        path: "{{ filedir_ansible }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Create dirs for host
      ansible.builtin.file:
        path: "{{ filedir_ansible }}/{{ ansible_hostname }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Copy ROOT/EXEC file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/root/exec/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy SHOREWALL config files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/shorewall/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy NETPLAN files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/netplan/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy IPSEC files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/ipsec* "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy OPENVPN files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/openvpn/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost

- name: backup shd
  hosts: shd
  vars:
    filedir_ansible: "/mnt/disk/backup/sd/shd"
  tasks:
    - name: Create dirs for group of hosts
      ansible.builtin.file:
        path: "{{ filedir_ansible }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Create dirs for host
      ansible.builtin.file:
        path: "{{ filedir_ansible }}/{{ ansible_hostname }}"
        state: directory
        mode: '0777'
      delegate_to: localhost
    - name: Copy ROOT/EXEC file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/root/exec/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy SSH config files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/ssh/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy NETPLAN files
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/netplan/ "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy FSTAB file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/fstab "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
    - name: Copy EXPORTS file
      shell: rsync --delete -avzR -e ssh root@"{{ ansible_host }}":/etc/exports "{{ filedir_ansible }}/{{ ansible_hostname }}"
      delegate_to: localhost
