- hosts: kube
  become: true
  strategy: free
  tasks:
    - name: Обновляем apt cache
      shell: 'apt-get clean && apt-get update'
    - name: Install packages
      apt: 
        pkg:
          - vim
          - htop
          - docker.io
    - name: Установка Kubernetes
      ansible.builtin.shell: |
        apt-get install -y apt-transport-https ca-certificates curl
        curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt-get install -y kubelet kubeadm kubectl --allow-change-held-packages
        apt-mark hold kubelet kubeadm kubectl
        mkdir /etc/docker
        exit 0
    - name: Change Docker daemon.json
      ansible.builtin.copy:
        src: /etc/ansible/daemon.json
        dest: /etc/docker/daemon.json
        follow: yes
    - name: Перезапускаем Docker
      shell: 'systemctl enable docker && systemctl daemon-reload && systemctl restart docker'
    - name: Отключаем swap на Ubuntu 18.04
      shell: 'if [ -f "/swap.img" ] ; then swapoff -v /swap.img; fi && sed -i /swap/d /etc/fstab && if [ -f "/swap.img" ] ; then rm /swap.img; fi'
